import type { Repository } from '../types/repo';

export const TOTAL_REPOS = 5756;
export const PER_PAGE_OPTIONS = [10, 25, 50, 100];
export const DEFAULT_PER_PAGE = 25;
export const NODE_DID = 'did:key:z6Mkicjkc95VcFx38Xg2SvFV2ENsu3dLDoWborjPGVodHXoH';

export const mockRepositories: Repository[] = [
  {
    id: 1,
    owner: 'z6MkwVfg',
    name: 'minebean-nostradamus',
    description: 'Append-only signed per-round decision log of the Nostradamus strategy agent',
    branch: 'main',
    updatedAt: '13s ago',
    createdAt: 'May 12, 2026',
    stars: 3,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 2, total: 3 },
    latestCommit: { hash: 'a3f8b2c1', shortHash: 'a3f8b2c', message: 'add round 47 decision log entry', time: '13s ago' },
    files: [
      { name: 'README.md', size: '2.1 KB', type: 'file' },
      { name: 'decisions', size: '—', type: 'dir' },
      { name: 'schema.json', size: '487 B', type: 'file' },
    ],
  },
  {
    id: 2,
    owner: 'z6MktsCk',
    name: 'chain-596283',
    description: 'automated repo',
    branch: 'main',
    updatedAt: '4m ago',
    createdAt: 'Jun 9, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 1, total: 3 },
    latestCommit: { hash: 'c4d9e0f1', shortHash: 'c4d9e0f', message: 'auto generated commit', time: '4m ago' },
    files: [
      { name: 'INFO.txt', size: '61 B', type: 'file' },
      { name: 'Token.sol', size: '430 B', type: 'file' },
    ],
  },
  {
    id: 3,
    owner: 'z6MkeyXD',
    name: 'chain-85084',
    description: 'auto generated repo',
    branch: 'main',
    updatedAt: '10m ago',
    createdAt: 'Jun 9, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 3, total: 3 },
    latestCommit: { hash: 'b1e2c3d4', shortHash: 'b1e2c3d', message: 'auto generated commit', time: '10m ago' },
    files: [
      { name: 'INFO.txt', size: '61 B', type: 'file' },
      { name: 'Token.sol', size: '430 B', type: 'file' },
    ],
  },
  {
    id: 4,
    owner: 'z6MkwVfg',
    name: 'minebean-stake',
    description: 'Hourly signed snapshots of BEAN staking state on Base',
    branch: 'main',
    updatedAt: '15m ago',
    createdAt: 'Apr 3, 2026',
    stars: 1,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 2, total: 3 },
    latestCommit: { hash: 'f9a0b1c2', shortHash: 'f9a0b1c', message: 'snapshot block 24189401', time: '15m ago' },
    files: [
      { name: 'README.md', size: '1.4 KB', type: 'file' },
      { name: 'snapshots', size: '—', type: 'dir' },
      { name: 'config.json', size: '218 B', type: 'file' },
    ],
  },
  {
    id: 5,
    owner: 'z6MkkFV2',
    name: 'montadordeguia',
    description: 'Montadordeguia',
    branch: 'main',
    updatedAt: '18m ago',
    createdAt: 'Jun 8, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 1, total: 3 },
    latestCommit: { hash: 'e7c8d9e0', shortHash: 'e7c8d9e', message: 'initial commit', time: '18m ago' },
    files: [
      { name: 'README.md', size: '892 B', type: 'file' },
      { name: 'main.py', size: '1.7 KB', type: 'file' },
    ],
  },
  {
    id: 6,
    owner: 'z6MkeyXD',
    name: 'quant-17854',
    description: 'auto generated repo',
    branch: 'main',
    updatedAt: '1h ago',
    createdAt: 'Jun 8, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 2, total: 3 },
    latestCommit: { hash: 'd3f4a5b6', shortHash: 'd3f4a5b', message: 'auto generated commit', time: '1h ago' },
    files: [
      { name: 'INFO.txt', size: '61 B', type: 'file' },
      { name: 'strategy.py', size: '512 B', type: 'file' },
    ],
  },
  {
    id: 7,
    owner: 'z6Mkh7Ln',
    name: 'can-you-make-me-site-like-netflix-i-will-upland-all-the',
    description: 'Can you make me site like Netflix I will upland all the content there',
    branch: 'main',
    updatedAt: '1h ago',
    createdAt: 'Jun 7, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 1, total: 3 },
    latestCommit: { hash: 'c2e3f4a5', shortHash: 'c2e3f4a', message: 'initial commit', time: '1h ago' },
    files: [
      { name: 'README.md', size: '234 B', type: 'file' },
    ],
  },
  {
    id: 8,
    owner: 'z6MkkgCm',
    name: 'quant-753223',
    description: 'automated repo',
    branch: 'main',
    updatedAt: '1h ago',
    createdAt: 'Jun 8, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 3, total: 3 },
    latestCommit: { hash: 'b0c1d2e3', shortHash: 'b0c1d2e', message: 'auto generated commit', time: '1h ago' },
    files: [
      { name: 'INFO.txt', size: '61 B', type: 'file' },
      { name: 'strategy.py', size: '512 B', type: 'file' },
    ],
  },
  {
    id: 9,
    owner: 'z6Mks248',
    name: 'nova-921795',
    description: 'automated repo',
    branch: 'main',
    updatedAt: '2h ago',
    createdAt: 'Jun 7, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 2, total: 3 },
    latestCommit: { hash: 'a9b0c1d2', shortHash: 'a9b0c1d', message: 'auto generated commit', time: '2h ago' },
    files: [
      { name: 'INFO.txt', size: '61 B', type: 'file' },
      { name: 'main.ts', size: '320 B', type: 'file' },
    ],
  },
  {
    id: 10,
    owner: 'z6MkeyXD',
    name: 'cyber-600792',
    description: 'auto generated repo',
    branch: 'main',
    updatedAt: '2h ago',
    createdAt: 'Jun 7, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 1, total: 3 },
    latestCommit: { hash: '9f0a1b2c', shortHash: '9f0a1b2', message: 'auto generated commit', time: '2h ago' },
    files: [
      { name: 'INFO.txt', size: '61 B', type: 'file' },
      { name: 'Token.sol', size: '430 B', type: 'file' },
    ],
  },
  {
    id: 11,
    owner: 'z6MkwJq6',
    name: 'hyper-862740',
    description: 'automated repo',
    branch: 'main',
    updatedAt: '2h ago',
    createdAt: 'Jun 7, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 2, total: 3 },
    latestCommit: { hash: '8e9f0a1b', shortHash: '8e9f0a1', message: 'auto generated commit', time: '2h ago' },
    files: [
      { name: 'INFO.txt', size: '61 B', type: 'file' },
      { name: 'node.ts', size: '788 B', type: 'file' },
    ],
  },
  {
    id: 12,
    owner: 'z6MkoTAF',
    name: 'research',
    description: 'mirrored from peer',
    branch: 'main',
    updatedAt: '2h ago',
    createdAt: 'Jun 1, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: true,
    drift: { agree: 3, total: 3 },
    latestCommit: { hash: '7d8e9f0a', shortHash: '7d8e9f0', message: 'mirror sync', time: '2h ago' },
    files: [
      { name: 'README.md', size: '4.2 KB', type: 'file' },
      { name: 'papers', size: '—', type: 'dir' },
    ],
  },
  {
    id: 13,
    owner: 'z6MkwVfg',
    name: 'minebean-logs',
    description: 'Structured event log export for BEAN protocol activity',
    branch: 'main',
    updatedAt: '3h ago',
    createdAt: 'Mar 18, 2026',
    stars: 2,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 2, total: 3 },
    latestCommit: { hash: '6c7d8e9f', shortHash: '6c7d8e9', message: 'export batch 1891', time: '3h ago' },
    files: [
      { name: 'README.md', size: '1.8 KB', type: 'file' },
      { name: 'logs', size: '—', type: 'dir' },
      { name: 'exporter.ts', size: '2.3 KB', type: 'file' },
      { name: 'schema.json', size: '614 B', type: 'file' },
    ],
  },
  {
    id: 14,
    owner: 'z6MkpQR9',
    name: 'delta-441920',
    description: 'automated repo',
    branch: 'main',
    updatedAt: '3h ago',
    createdAt: 'Jun 6, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 1, total: 3 },
    latestCommit: { hash: '5b6c7d8e', shortHash: '5b6c7d8', message: 'auto generated commit', time: '3h ago' },
    files: [
      { name: 'INFO.txt', size: '61 B', type: 'file' },
      { name: 'Token.sol', size: '430 B', type: 'file' },
    ],
  },
  {
    id: 15,
    owner: 'z6MkLx7T',
    name: 'sigma-core',
    description: 'Core runtime for sigma nodes — handles scheduling, state sync, and peer negotiation',
    branch: 'main',
    updatedAt: '4h ago',
    createdAt: 'Feb 5, 2026',
    stars: 7,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 3, total: 3 },
    latestCommit: { hash: '4a5b6c7d', shortHash: '4a5b6c7', message: 'fix peer negotiation timeout on slow connections', time: '4h ago' },
    files: [
      { name: 'README.md', size: '6.1 KB', type: 'file' },
      { name: 'src', size: '—', type: 'dir' },
      { name: 'tests', size: '—', type: 'dir' },
      { name: 'package.json', size: '1.2 KB', type: 'file' },
      { name: 'tsconfig.json', size: '418 B', type: 'file' },
    ],
  },
  {
    id: 16,
    owner: 'z6MkBv3W',
    name: 'quant-991234',
    description: 'auto generated repo',
    branch: 'main',
    updatedAt: '5h ago',
    createdAt: 'Jun 5, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 2, total: 3 },
    latestCommit: { hash: '3f4a5b6c', shortHash: '3f4a5b6', message: 'auto generated commit', time: '5h ago' },
    files: [
      { name: 'INFO.txt', size: '61 B', type: 'file' },
      { name: 'strategy.py', size: '512 B', type: 'file' },
    ],
  },
  {
    id: 17,
    owner: 'z6MkrFm2',
    name: 'peer-sync',
    description: 'Lightweight daemon for automated peer discovery and repository synchronization',
    branch: 'main',
    updatedAt: '6h ago',
    createdAt: 'Jan 20, 2026',
    stars: 4,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 2, total: 3 },
    latestCommit: { hash: '2e3f4a5b', shortHash: '2e3f4a5', message: 'retry backoff on connection refused', time: '6h ago' },
    files: [
      { name: 'README.md', size: '3.4 KB', type: 'file' },
      { name: 'daemon.rs', size: '8.1 KB', type: 'file' },
      { name: 'config.toml', size: '340 B', type: 'file' },
      { name: 'Cargo.toml', size: '892 B', type: 'file' },
    ],
  },
  {
    id: 18,
    owner: 'z6MkeyXD',
    name: 'chain-77021',
    description: 'auto generated repo',
    branch: 'main',
    updatedAt: '7h ago',
    createdAt: 'Jun 4, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 1, total: 3 },
    latestCommit: { hash: '1d2e3f4a', shortHash: '1d2e3f4', message: 'auto generated commit', time: '7h ago' },
    files: [
      { name: 'INFO.txt', size: '61 B', type: 'file' },
      { name: 'Token.sol', size: '430 B', type: 'file' },
    ],
  },
  {
    id: 19,
    owner: 'z6MkNzQ4',
    name: 'atlas-887213',
    description: 'automated repo',
    branch: 'main',
    updatedAt: '8h ago',
    createdAt: 'Jun 3, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 3, total: 3 },
    latestCommit: { hash: '0c1d2e3f', shortHash: '0c1d2e3', message: 'auto generated commit', time: '8h ago' },
    files: [
      { name: 'INFO.txt', size: '61 B', type: 'file' },
      { name: 'main.ts', size: '320 B', type: 'file' },
    ],
  },
  {
    id: 20,
    owner: 'z6MkwVfg',
    name: 'minebean-oracle',
    description: 'Price oracle aggregator with multi-source validation and signed attestations',
    branch: 'main',
    updatedAt: '10h ago',
    createdAt: 'Mar 1, 2026',
    stars: 5,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 2, total: 3 },
    latestCommit: { hash: 'fb0c1d2e', shortHash: 'fb0c1d2', message: 'add chainlink feed as secondary source', time: '10h ago' },
    files: [
      { name: 'README.md', size: '4.7 KB', type: 'file' },
      { name: 'src', size: '—', type: 'dir' },
      { name: 'feeds.json', size: '1.1 KB', type: 'file' },
      { name: 'package.json', size: '934 B', type: 'file' },
    ],
  },
  {
    id: 21,
    owner: 'z6MkjH8S',
    name: 'nexus-329401',
    description: 'automated repo',
    branch: 'main',
    updatedAt: '12h ago',
    createdAt: 'Jun 2, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 2, total: 3 },
    latestCommit: { hash: 'ea0b1c2d', shortHash: 'ea0b1c2', message: 'auto generated commit', time: '12h ago' },
    files: [
      { name: 'INFO.txt', size: '61 B', type: 'file' },
      { name: 'node.ts', size: '788 B', type: 'file' },
    ],
  },
  {
    id: 22,
    owner: 'z6MkCs1P',
    name: 'vault-index',
    description: 'Encrypted key-value store with merkle proofs and append-only audit log',
    branch: 'main',
    updatedAt: '14h ago',
    createdAt: 'Dec 14, 2025',
    stars: 9,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 3, total: 3 },
    latestCommit: { hash: 'd9eafb0c', shortHash: 'd9eafb0', message: 'add proof verification for batch reads', time: '14h ago' },
    files: [
      { name: 'README.md', size: '7.8 KB', type: 'file' },
      { name: 'src', size: '—', type: 'dir' },
      { name: 'tests', size: '—', type: 'dir' },
      { name: 'Cargo.toml', size: '1.4 KB', type: 'file' },
      { name: 'LICENSE', size: '1.1 KB', type: 'file' },
    ],
  },
  {
    id: 23,
    owner: 'z6MktsCk',
    name: 'chain-102847',
    description: 'automated repo',
    branch: 'main',
    updatedAt: '18h ago',
    createdAt: 'May 28, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 1, total: 3 },
    latestCommit: { hash: 'c8d9eafb', shortHash: 'c8d9eaf', message: 'auto generated commit', time: '18h ago' },
    files: [
      { name: 'INFO.txt', size: '61 B', type: 'file' },
      { name: 'Token.sol', size: '430 B', type: 'file' },
    ],
  },
  {
    id: 24,
    owner: 'z6MkqYE6',
    name: 'nano-771039',
    description: 'auto generated repo',
    branch: 'main',
    updatedAt: '22h ago',
    createdAt: 'May 25, 2026',
    stars: 0,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 2, total: 3 },
    latestCommit: { hash: 'b7c8d9ea', shortHash: 'b7c8d9e', message: 'auto generated commit', time: '22h ago' },
    files: [
      { name: 'INFO.txt', size: '61 B', type: 'file' },
      { name: 'main.ts', size: '320 B', type: 'file' },
    ],
  },
  {
    id: 25,
    owner: 'z6MkMvD3',
    name: 'proto-mesh',
    description: 'Distributed mesh protocol handler for dynamic peer topology management',
    branch: 'main',
    updatedAt: '1d ago',
    createdAt: 'Nov 3, 2025',
    stars: 6,
    visibility: 'public',
    isMirror: false,
    drift: { agree: 2, total: 3 },
    latestCommit: { hash: 'a6b7c8d9', shortHash: 'a6b7c8d', message: 'handle partitioned topology gracefully', time: '1d ago' },
    files: [
      { name: 'README.md', size: '5.3 KB', type: 'file' },
      { name: 'src', size: '—', type: 'dir' },
      { name: 'proto', size: '—', type: 'dir' },
      { name: 'go.mod', size: '612 B', type: 'file' },
      { name: 'Makefile', size: '1.8 KB', type: 'file' },
    ],
  },
];
